Rails.application.routes.draw do
  
  resources :keys 
  #Resource oriented routing allows for much of the routing to be generated by rails.
  #For a more detailed explanation, visit http://guides.rubyonrails.org/routing.html (you'll need it!)
  resources :assets do
    #Member routes add routes designed for single objects to the resource, allowing rails to 
    #generate extra routes for these actions.
    member do
      get 'sharing'
      post 'share'
      get 'share_index' 
      patch 'password_input'
      patch 'password_input_shared'
      get 'enter_password'
      get 'enter_password_shared'
      #share_index displays the users that a file has been shared too
    end
    #Collection routes add routes designed for multiple objects to the resource, allowing rails to 
    #generate extra routes for these actions.
    collection do
      get 'shared_files'
    end
  end
  
  get 'sessions/new'

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/files', to: "static_pages#file_upload"
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
    
  delete '/assets/:id/unshare/:sId', to:  'assets#unshare', as: :unshare_asset

  #sharing renders the form, share takes the post request
  #Session routing
  
  resources :users
   
   #Generates helper methods such as signup_path
=begin
  Declares all common routes for the controller User:
  /users          -> GET, POST
  /users/new      -> GET
  /users/:id      -> GET, PUT/PATCH, DELETE 
  /users/:id/edit -> GET
  
  See http://guides.rubyonrails.org/routing.html#crud-verbs-and-actions for reference
=end
  
end
